language: node_js

node_js:
- '0.12'

branches:
  only:
  - master

notifications:
  slack: dasix:roV0ekeggkEYugjwMwsmebrm
  email:
    on_failure: always

before_install:
- chmod +x ./scripts -R

before_deploy:
- npm run-script grits

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: dasix.com
  local-dir: dist
  acl: public_read
  skip_cleanup: true
  on:
    repo: Dasix/site-dasix.com